
export const regions = [
  "Toshkent shahri",
  "Toshkent viloyati",
  "Andijon viloyati",
  "Buxoro viloyati",
  "Farg'ona viloyati",
  "Jizzax viloyati",
  "Namangan viloyati",
  "Navoiy viloyati",
  "Qashqadaryo viloyati",
  "Qoraqalpog'iston Respublikasi",
  "Samarqand viloyati",
  "Sirdaryo viloyati",
  "Surxondaryo viloyati",
  "Xorazm viloyati"
];

export const districts: Record<string, string[]> = {
  "Toshkent shahri": [
    "Bektemir tumani",
    "Chilonzor tumani",
    "Hamza tumani",
    "Mirobod tumani",
    "Mirzo Ulug'bek tumani",
    "Olmazor tumani",
    "Sergeli tumani",
    "Shayxontohur tumani",
    "Uchtepa tumani",
    "Yakkasaroy tumani",
    "Yunusobod tumani"
  ],
  "Toshkent viloyati": [
    "Angren shahri",
    "Bekobod shahri",
    "Chirchiq shahri",
    "Olmaliq shahri",
    "Ohangaron tumani",
    "Bekobod tumani",
    "Bo'stonliq tumani",
    "Bo'ka tumani",
    "Chinoz tumani",
    "Qibray tumani",
    "Parkent tumani",
    "Piskent tumani",
    "Quyi Chirchiq tumani",
    "O'rta Chirchiq tumani",
    "Yangiyo'l tumani",
    "Yuqori Chirchiq tumani",
    "Zangiota tumani"
  ],
  "Andijon viloyati": [
    "Andijon shahri",
    "Andijon tumani",
    "Asaka tumani",
    "Baliqchi tumani",
    "Bo'z tumani",
    "Buloqboshi tumani",
    "Izboskan tumani",
    "Jalaquduq tumani",
    "Marhamat tumani",
    "Oltinko'l tumani",
    "Paxtaobod tumani",
    "Qo'rg'ontepa tumani",
    "Shahrixon tumani",
    "Ulug'nor tumani",
    "Xo'jaobod tumani"
  ],
  "Buxoro viloyati": [
    "Buxoro shahri",
    "Buxoro tumani",
    "G'ijduvon tumani",
    "Jondor tumani",
    "Kogon tumani",
    "Kogon shahri",
    "Qorako'l tumani",
    "Qorovulbozor tumani",
    "Olot tumani",
    "Peshku tumani",
    "Romitan tumani",
    "Shofirkon tumani",
    "Vobkent tumani"
  ],
  "Farg'ona viloyati": [
    "Farg'ona shahri",
    "Farg'ona tumani",
    "Beshariq tumani",
    "Bag'dod tumani",
    "Buvayda tumani",
    "Dang'ara tumani",
    "Furqat tumani",
    "Oltiariq tumani",
    "O'zbekiston tumani",
    "Quva tumani",
    "Quvasoy shahri",
    "Qo'qon shahri",
    "Qo'shtepa tumani",
    "Rishton tumani",
    "So'x tumani",
    "Toshloq tumani",
    "Uchko'prik tumani",
    "Yozyovon tumani"
  ],
  "Jizzax viloyati": [
    "Jizzax shahri",
    "Arnasoy tumani",
    "Baxmal tumani",
    "Do'stlik tumani",
    "Forish tumani",
    "G'allaorol tumani",
    "Sharof Rashidov tumani",
    "Mirzacho'l tumani",
    "Paxtakor tumani",
    "Yangiobod tumani",
    "Zafarobod tumani",
    "Zarbdor tumani",
    "Zomin tumani"
  ],
  "Namangan viloyati": [
    "Namangan shahri",
    "Namangan tumani",
    "Chortoq tumani",
    "Chust tumani",
    "Kosonsoy tumani",
    "Mingbuloq tumani",
    "Norin tumani",
    "Pop tumani",
    "To'raqo'rg'on tumani",
    "Uychi tumani",
    "Uchqo'rg'on tumani",
    "Yangiqo'rg'on tumani"
  ],
  "Navoiy viloyati": [
    "Navoiy shahri",
    "Navbahor tumani",
    "Karmana tumani",
    "Konimex tumani",
    "Qiziltepa tumani",
    "Nurota tumani",
    "Tomdi tumani",
    "Uchquduq tumani",
    "Xatirchi tumani",
    "Zarafshon shahri"
  ],
  "Qashqadaryo viloyati": [
    "Qarshi shahri",
    "Qarshi tumani",
    "Chiroqchi tumani",
    "Dehqonobod tumani",
    "G'uzor tumani",
    "Kasbi tumani",
    "Kitob tumani",
    "Koson tumani",
    "Mirishkor tumani",
    "Muborak tumani",
    "Nishon tumani",
    "Qamashi tumani",
    "Shahrisabz tumani",
    "Shahrisabz shahri",
    "Yakkabog' tumani"
  ],
  "Qoraqalpog'iston Respublikasi": [
    "Nukus shahri",
    "Amudaryo tumani",
    "Beruniy tumani",
    "Chimboy tumani",
    "Ellikqala tumani",
    "Kegeyli tumani",
    "Mo'ynoq tumani",
    "Nukus tumani",
    "Qanliko'l tumani",
    "Qo'ng'irot tumani",
    "Qorao'zak tumani",
    "Shumanay tumani",
    "Taxtako'pir tumani",
    "To'rtko'l tumani",
    "Xo'jayli tumani",
    "Taxiatosh shahri"
  ],
  "Samarqand viloyati": [
    "Samarqand shahri",
    "Samarqand tumani",
    "Bulung'ur tumani",
    "Ishtixon tumani",
    "Jomboy tumani",
    "Kattaqo'rg'on tumani",
    "Kattaqo'rg'on shahri",
    "Narpay tumani",
    "Nurobod tumani",
    "Oqdaryo tumani",
    "Paxtachi tumani",
    "Payariq tumani",
    "Pastdarg'om tumani",
    "Toyloq tumani",
    "Urgut tumani"
  ],
  "Sirdaryo viloyati": [
    "Guliston shahri",
    "Guliston tumani",
    "Boyovut tumani",
    "Mirzaobod tumani",
    "Oqoltin tumani",
    "Sardoba tumani",
    "Sayxunobod tumani",
    "Sirdaryo tumani",
    "Shirin shahri",
    "Xovos tumani",
    "Yangiyer shahri"
  ],
  "Surxondaryo viloyati": [
    "Termiz shahri",
    "Termiz tumani",
    "Angor tumani",
    "Boysun tumani",
    "Denov tumani",
    "Jarqo'rg'on tumani",
    "Muzrabot tumani",
    "Oltinsoy tumani",
    "Qiziriq tumani",
    "Qumqo'rg'on tumani",
    "Sariosiyo tumani",
    "Sherobod tumani",
    "Sho'rchi tumani",
    "Uzun tumani"
  ],
  "Xorazm viloyati": [
    "Urganch shahri",
    "Urganch tumani",
    "Bog'ot tumani",
    "Gurlan tumani",
    "Xiva tumani",
    "Xiva shahri",
    "Xonqa tumani",
    "Hazorasp tumani",
    "Qo'shko'pir tumani",
    "Shovot tumani",
    "Yangiariq tumani",
    "Yangibozor tumani"
  ]
};
